### ISSUE TITLE
Publish to NPM and usage example

### ISSUE THREAD

**Issue by Extarys** [sjudson/paseto.js#1]
You should Publish to NPM and add usage example :smile: Even if you tag it with version 0.3.0 or something.

Thanks for this!

**Comment by sjudson** [comment]
Yep. I have to bring up some last bits of parity for the low level API and add some docs, then will ship version `0.1.0` onto NPM.

**Comment by sjudson** [comment]
Release `0.1.0` now on `npm`: https://www.npmjs.com/package/paseto.js
