### ISSUE TITLE
yarn add doesn't work with python 3

### ISSUE THREAD

**Issue by vogt31337** [sjudson/paseto.js#11]
Hi,

for some reason during yarn add paseto.js, the installer executed some python 2 code. Which isn't compatible with python 3, maybe add a routine to detect the python version and call the corresponding code.

BR

**Comment by sjudson** [comment]
Sorry for not responding earlier. I'm a bit short of time at present, and as this can be worked around (temporarily relinking python) I'm not able to prioritize it. I'll make sure to take care of it next time I get around to making library changes, and would be more than happy to accept a PR in the interim.

**Comment by vogt31337** [comment]
@sjudson I found out that the problem is with node-gyp, they are using python2.7 and they stated that somehow the python interpreter can be passed as a parameter.

So as this bug is not related to paseto.js, I will close it.
