### ISSUE TITLE
how to set notBefore, Expiration field 

### ISSUE THREAD

**Issue by matth-c3** [sjudson/paseto.js#20]
Hello, 

How to set the notBefore and Expiration field ? 

Also is it possible to import a private rsa key ? 

Thanks by advance.

**Comment by sjudson** [comment]
Not at present, that'll be part of the high level API that's still be worked on. At the moment this library just provides the cryptographic serialization, not any internal data structures.

**Comment by matth-c3** [comment]
Hello @sjudson , do you know when it will be :) ?

**Comment by sjudson** [comment]
There's an open PR (https://github.com/sjudson/paseto.js/pull/17) for it that I hope to look at early next month.
