### ISSUE TITLE
V1 Public Signed Token not able be verified by JAVA Public V1 verify (paseto4j)

### ISSUE THREAD

**Issue by nickfai936** [sjudson/paseto.js#21]
Hi, I am new to paseto. I recently using the paseto (javascript) and was able to sign and verify with my own private and public keys but when other people who use JAVA paseto4j to verify the signed token and it will prompts invalid signature error.
The strange thing is, I was able to verify the signed token by JAVA paseto4j with the same Javascript paseto codes.

**Comment by sjudson** [comment]
So you're saying that the Java implementation verifies its own tokens correctly, as does this, and this verifies the Java tokens, but the tokens from this aren't verified by the Java implementation? Could you file an issue there? I'm not saying the issue couldn't be on this end, but I don't really have any way to look into it.

**Comment by sjudson** [comment]
I'm going to close this for now. If you find out any more specific information you're welcome to reopen it.
