### ISSUE TITLE
High-level api

### ISSUE THREAD

**Issue by Extarys** [sjudson/paseto.js#27]
I wanted to know how the `high-level api` talked about in the readme is coming along and if it was still on the table.

**Comment by sjudson** [comment]
It's definitely on the table, but my work on this library besides maintenance is limited by time. There's an open PR (#17) at the moment working towards it, but it doesn't entirely fit the approach I'd like to see to the code structure and I'd need to substantially rework it in a branch before merging. At some point I'd like to sit down, reevaluate it, and decide between doing so or just starting my own approach, but again, am unsure as to when I'll have the opportunity to do so.

**Comment by Extarys** [comment]
I understand. I always have a similar issue.

Thanks for your reply. I'll follow the PR.
