### ISSUE TITLE
Store key as string and convert back to Key instance

### ISSUE THREAD

**Issue by katp4** [sjudson/paseto.js#3]
Hi,

First of all thanks for this, it has been very useful.

I want to store the key generated by `return encoder.symmetric()` to a mongoDB database as a string, retrieve it and then use it to decrypt data. However, when storing it as string, it loses all of its attached properties i.e key.protocol().

Do you have any suggestions on how to do this? Is there a function i can use/expose i.e StringToV2?

**Comment by katp4** [comment]
Scratch that, solved it with the inject function :)

**Comment by Extarys** [comment]
Hey @katp4, can you tell me how you did this? I thought the key was a string, but it's an object, quite hard to store easily, would prefer a simple string instead of this mess :cry:

**Comment by Extarys** [comment]
Oh just found out I can use crypto to generate a key and use that one like you said! XD

```
const keyRaw = Buffer.from(
		"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
		"hex"
	)
	const sk = new Paseto.SymmetricKey(new Paseto.V2())

	sk.inject(keyRaw)

	// const encoder = new Paseto.V2()
	const encoder = sk.protocol()

	// const sk = await encoder.symmetric()
	const token = await encoder.encrypt(message, sk)

	console.log(message)
	console.log(token)

	return token
```

**Comment by sjudson** [comment]
@Extarys - You can extract the raw key buffer using the corresponding `.raw()` method - https://github.com/sjudson/paseto.js/blob/master/lib/key/symmetric.js#L182-L195

The use of an object instead of a raw string is intentional - it allows additional validation to be required before a key may be used, and also reduces the propensity for mishaps with improper passing/use of keying material.

**Comment by Extarys** [comment]
Thank you @sjudson for that! I understand the why, I just find the documentation in the readme hard to understand when you are not to familiar with it. That's where answers like yours help me a lot.

Thanks again.
